### ISSUE TITLE
Paper suggestion: Gesture Recognition in Robotic Surgery With Multimodal Attention

### ISSUE THREAD

**Issue by JieYingWu** [dcmoyer/vu-ml-reading-group#9]
For utterly selfish reasons since I have recently developed a keen interest in gesture and skill recognition. 

https://ieeexplore.ieee.org/abstract/document/9701436?casa_token=4rtywSRJLwEAAAAA:VPJ4DMPfeGHMd2Jhnp3btZqG2O7ur0PNXlf9uWDEZhmw5iPvze4Tindh08xjQ9Ob7Igexvo-jw

**Comment by dcmoyer** [comment]
Read in group.
